### PR TITLE
Update for new systemd.

### PR DESCRIPTION
**Pull request by arekm**
Changes:
* Update for new systemd.

### CODE REVIEW

**Comment by glensc** [comment]
avoid commit messages and pull request titles like "update to new", include actual version value what is "new".

**Comment by arekm** [comment]
Commit message content says that.

**Comment by glensc** [comment]
it's called click-baiting to force clicking on commit diff to understand the change. that's the commit message is for, to summarize commit content.

you could just commit next time `-m "changes"`

**Comment by glensc** [comment]
and in fact, commit diff does not indicate what is the "new systemd version":
- https://github.com/Jajcus/pld-new-rescue/pull/14/files

**Comment by arekm** [comment]
Read commit message:

"Update for newer systemd.

Newer (>= 242) systemd doesn't provide few symlinks by default (see
systemd NEWS) and requires "systemctl preset-all" to be called.
"

**Comment by glensc** [comment]
image

and is similar for git shortlog

**Comment by Jajcus** [comment]
I guess I'll just accept that and let you continue in the Arek's repository (https://github.com/arekm/pld-new-rescue).

**Comment by glensc** [comment]
Why fork? just give permissions to the fellow pld developer.

or if abandoning, transfer to new owner. so the issues and history persist. currently arekm repo doesn't even have issues enabled.

also, I see that the commit that supposed to be in fork, also landed here: 146cd0ffb937562b82d218849daad2828be9e4c3

**Comment by Jajcus** [comment]
> Why fork? just give permissions to the fellow pld developer.

https://github.com/Jajcus/ is my personal namespace on GitHub. As I am not going to maintain this project any more, it does not belong here any longer.

Ideally it should be moved under a PLD namespace, where multiple developers could develop it.

> also, I see that the commit that supposed to be in fork, also landed here: 146cd0f

Actually it is the commit I made this merge for. In fact I should update the README myself to point to the fork or something, but I am _that_ lazy, it seems.

When I find some time to do things properly, I will update the README and archive the project.

**Comment by glensc** [comment]
> @Jajcus is my personal namespace on GitHub. As I am not going to maintain this project any more, it does not belong here any longer.

That's why I said, transfer to a new owner:

- https://docs.github.com/en/github/administering-a-repository/transferring-a-repository

> Ideally it should be moved under a PLD namespace, where multiple developers could develop it.

this is where it got complicated, @pld-linux org is for rpm packages only (supposed to be readonly mirror), need new organization for "projects". that's why just transferring to a new owner is the best.

**Comment by Jajcus** [comment]
@arekm what do you think? Would you like the project transferred to you?

**Comment by arekm** [comment]
Can we rename pld-linux to pld-linux-packages and introduce new pld-linux for regular projects and transfer pld-new-rescue there?

**Comment by glensc** [comment]
renaming @pld-linux should be the very-very last choice, it contains ~22k packages. Besides the obvious problems that all push URLs need to be reconfigured, other unknown issues from our infra doing synchronizing, half internet re-indexed, there will be very very likely unknown problems from the GitHub side of rename of this magnitude.

**Comment by arekm** [comment]
Right. Adding new "pld-linux.org" instead?

btw. when project is transferred do old urls redirect to new location?

**Comment by glensc** [comment]
Yes, if transferred, URLs redirect. but as you already have a fork, you have to rename or delete that fork before transfer.

**Pull request merged**
